[package]
name = "typst-analyzer"
edition = "2021"
version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true

[dependencies]
thiserror = "2.0.9"
dashmap = "6.1.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
tower-lsp = "0.20.0"
tracing-subscriber = "0.3.19"
regex = "1.11.1"

[lints]
workspace = true
