# YAML is the best option here since we don't need to worry about escape characters and indentation.
# YAML will preserve indentation if we use the `|` symbol.
# The `1` in ${1:100} specifies the cursor position after the insertion of the snippet,
# and the 100 is a placeholder text (a hint for the user on what value to input there). 
# We can also add a default value if needed.
snippets:
  - label: "custom_line"
    details: "Insert a thin line"
    insert_text: | 
      #line(
        length: ${1:100}%,
        stroke: (
          paint: rgb("#757575"),
          thickness: 0.1pt,
        )
      )
  - label: "custom_time"
    details: "Insert a custom time snippet"
    insert_text: "#time(hour: 12, minute: 30, second: 45)"
